version: '3'

services:
  pixelflut-server:
    image: docker.io/sbernauer/breakwater:0.12.0
    restart: unless-stopped
    entrypoint: [ "breakwater", "-l", "[::]:1234", "--vnc-port", "5900", "--prometheus-listen-address", "127.0.0.1:9991" ]
    command: --width 1920 --height 1080 --text "Hacktoberfest 2023 - Crazy Canvas"
    network_mode: "host"

  test-pixelflut-server:
    image: docker.io/sbernauer/breakwater:0.12.0
    restart: unless-stopped
    entrypoint: [ "breakwater", "-l", "[::]:4321", "--vnc-port", "5901", "--prometheus-listen-address", "127.0.0.1:9992" ]
    command: --width 1280 --height 720 --text "Hacktoberfest 2023 - Test Canvas"
    network_mode: "host"

  pixelflut-playground:
    image: ghcr.io/poeschl/pixelflut-challenge-playground:latest
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --controlport 8888"
    network_mode: "host"
  
  pixelflut-labyrinth:
    image: ghcr.io/poeschl/pixelmaze:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 -x 640 -y 360 --width 640 --height 360 --timer 600 --blank --cellsize 16 --draw-marker --horns-of-jericho"
    network_mode: "host"

  # Top left
  pixelflut-cubedrawer-1:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 11 --soy 191 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"
  
  # Top middle
  pixelflut-cubedrawer-2:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 651 --soy 191 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"
  
  # Top right
  pixelflut-cubedrawer-3:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 1291 --soy 191 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"

  # Middle left
  pixelflut-cubedrawer-4:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 11 --soy 551 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"

  # Middle right
  pixelflut-cubedrawer-5:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 1291 --soy 551 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"

  # Bottom left
  pixelflut-cubedrawer-6:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 11 --soy 911 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --sy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"
  
  # Bottom middle
  pixelflut-cubedrawer-7:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 651 --soy 911 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 2"
    network_mode: "host"

  # Bottom right
  pixelflut-cubedrawer-8:
    image: ghcr.io/hacktoberfestmunich/cubemover:dev
    restart: unless-stopped
    command: "--host 127.0.0.1 --port 1234 --sox 1291 --soy 911 --sw 300 --sh 150 --ow 29 --oh 17 --dx 1 --dy 1 --cf 'bada55' --cb '000000' --d 0.2"
    network_mode: "host"

  watchtower:
    image: docker.io/containrrr/watchtower:1.5.3
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--interval 60 --cleanup --label-enable"
  
  ############################################################

  pixelflut-team-brown_independents:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:brown_independents
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-yellow_pirates:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:yellow_pirates
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-white_dodgers:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:white_dodgers
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-red_titans:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:red_titans
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-purple_saints:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:purple_saints
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-pink_hotspurs:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:pink_hotspurs
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-green_twins:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:green_twins
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"

  pixelflut-team-ginger_mariners:
    image: ghcr.io/hacktoberfestmunich/hacktoberfest-2023:ginger_mariners
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    network_mode: "host"
